[window]
title = "Alacritty"
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true

[font]
normal = { family = "BigBlueTermPlus Nerd Font Propo", style = "Regular" }
bold   = { family = "BigBlueTermPlus Nerd Font Propo", style = "Bold" }
italic = { family = "BigBlueTermPlus Nerd Font Propo", style = "Italic" }
bold_italic = { family = "BigBlueTermPlus Nerd Font Propo", style = "Bold Italic" }
size = 13.0

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"

[terminal.shell]
program = "powershell.exe"
args = ["-NoLogo"]

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]
